# Generated by Django 5.1 on 2024-09-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
